const BrandData = [
  {
    id: 1000,
    title: "Denim Classic Button-Down Shirt",
    desc: "Crafted completely from cotton, this denim button-down shirt is a lightweight layer above classic outfits. Styled with long sleeves and a point collar. Designed with a patch pocket at the upper chest and finished with topstitching details.",
    image: "/Calvin/calvin1.webp",
    price: "2000",
  },
  {
    id: 1001,
    title: "90s Loose Fit Jeans",
    desc: "Inspired by denim trends from the 90s, this jean is styled with a loose fit and a medium rise waist. Crafted completely from cotton for a sturdy feel that will break-in over time. Designed with classic 5-pocket styling and finished with a CK monogram logo patch at the back waist.",
    image: "/Calvin/calvin2.webp",
    price: "1500",
  },
  {
    id: 1002,
    title: "Twill Logo Cap",
    desc: "A cotton twill cap made with 6 panel shaping and an adjustable back for a personalized fit. Designed with CK logo embroidery at the front.",
    image: "/Calvin/calvin3.webp",
    price: "700",
  },
  {
    id: 1003,
    title: "Slim fit Jeans",
    desc: "An iconic essential, these reimagined jeans are made with flexible stretch denim for enhanced movement and all-day comfort. Updated with heritage inspired logo accents and an iconic logo jacron paper patch at the back waist. Cut in a slim fit with considered detailing and reinforced seams.",
    image: "/Calvin/calvin4.webp",
    price: "1700",
  },
  {
    id: 1004,
    title: "Men's Jack Dress Shoe",
    desc: "Designed with a round shaped toe, these dress shoes are a formal, elevated silhouette. Detailed with lace-up styling and features a padded logo footbed.",
    image: "/Casual/formal9.webp",
    price: "2700",
  },
  {
    id: 1005,
    title: "Signature Chino",
    desc: "Styled in a slim fit, these chino pants are a versatile piece suited for both elevated and casual outfits. Crafted from a cotton stretch blend for breathable comfort and effortless wear. Made with a medium rise waist and slip pockets at both sides.",
    image: "/Calvin/calvin6.webp",
    price: "1700",
  },
  {
    id: 1006,
    title: "Monogram Logo Relaxed Fleece Crewneck Sweatshirt",
    desc: "Styled in an oversized silhouette, this crewneck sweatshirt is made with drop shoulders for a relaxed fit. Crafted from a cotton fleece blend for soft, plush comfort. Detailed with banded cuffs at the sleeve openings and features a CK monogram logo design at the front.",
    image: "/Calvin/calvin7.webp",
    price: "4700",
  },
  {
    id: 1007,
    title: "Tech Knit Quarter Zip Sweater",
    desc: "Woven with a half milano knit, this Calvin Klein pullover sweater features a standout rib-knit neck and a smooth body. Perfect as a layering piece, this top is finished with a stand collar, a 1/4 zip closure, long raglan sleeves and saddle shoulder construction.",
    image: "/Calvin/calvin8.webp",
    price: "3700",
  },
  {
    id: 1008,
    title: "Monogram Logo Relaxed Fleece Crewneck Sweatshirt",
    desc: "Styled in an oversized silhouette, this crewneck sweatshirt is made with drop shoulders for a relaxed fit. Crafted from a cotton fleece blend for soft, plush comfort. Detailed with banded cuffs at the sleeve openings and features a CK monogram logo design at the front.",
    image: "/Calvin/calvin9.webp",
    price: "2900",
  },
  {
    id: 1009,
    title: "Cotton Stretch Classic Fit Pants",
    desc: "An elegant choice perfect for warmer temperatures, these Calvin Klein pants are made from a cotton stretch blend for a breathable, flexible design. Tailored in a classic fit with 5-pocket styling, a top button closure and straight legs. Pair these with the Cotton Stretch Classic Fit Blazer to complete the full suit.",
    image: "/Calvin/calvin10.webp",
    price: "6400",
  },
  {
    id: 2000,
    title: " TOBACCO COLLECTION RICH WARM ADDICTIVE 100 ML / 3.38 OZ",
    desc: "We work with monitoring programmes to ensure compliance with our social, environmental and health and safety standards for our products. To assess compliance, we have developed a programme of audits and continuous improvement plans.",
    image: "/Zara/zara1.jpg",
    price: "1500",
  },
  {
    id: 2001,
    title: "JOGGER WAIST CARGO TROUSERS",
    desc: "We work with monitoring programmes to ensure compliance with our social, environmental and health and safety standards for our products. To assess compliance, we have developed a programme of audits and continuous improvement plans.",
    image: "/Zara/zara2.jpg",
    price: "2290",
  },
  {
    id: 2002,
    title: "FAUX LEATHER BIKER JACKET",
    desc: "We work with monitoring programmes to ensure compliance with our social, environmental and health and safety standards for our products. To assess compliance, we have developed a programme of audits and continuous improvement plans.",
    image: "/Zara/zara3.jpg",
    price: "6990",
  },
  {
    id: 2003,
    title: "COWBOY BOOTS WITH BUCKLE",
    desc: "We work with monitoring programmes to ensure compliance with our social, environmental and health and safety standards for our products. To assess compliance, we have developed a programme of audits and continuous improvement plans.",
    image: "/Zara/zara4.jpg",
    price: "5990",
  },
  {
    id: 2004,
    title: "BOMBER JACKET WITH CONTRAST PATCH",
    desc: "Varsity jacket featuring a collar with elasticated trim and long sleeves. Welt hip pockets and an inside pocket. Contrast embroidery appliqué and patch on the front and back. Ribbed trims. Snap-button front.",
    image: "/Zara/zara5.jpg",
    price: "4290",
  },
  {
    id: 2005,
    title: "RETRO MULTI-PIECE SNEAKERS",
    desc: "Sneakers. Combination of materials, pieces and colours on the upper. Six-eyelet facing. Irregular and chunky sole.",
    image: "/Zara/zara6.jpg",
    price: "2890",
  },
  {
    id: 2006,
    title: "FAUX SUEDE JACKET",
    desc: "Collared jacket with long sleeves and buttoned cuffs. Flap pockets on the chest and welt pockets at the hip. Button-up front.",
    image: "/Zara/zara7.jpg",
    price: "7990",
  },
  {
    id: 2007,
    title: "SOFT WASH STRAIGHT FIT JEANS",
    desc: "Straight fit jeans with five pockets. Faded effect. Front button fastening. Button fly. Made of soft wash denim.",
    image: "/Zara/zara8.jpg",
    price: "3290",
  },
  {
    id: 2008,
    title: "Hoodie",
    desc: "Hoodie made of cotton with a napped interior. Adjustable hood and long sleeves. Front pouch pocket and ribbed trims.",
    image: "/Zara/zara9.jpg",
    price: "1890",
  },
  {
    id: 2009,
    title: "BOMBER JACKET WITH PATCHES",
    desc: "Varsity jacket with padded interior. Elasticated ribbed collar. Long sleeves in contrast leather effect fabric. Jetted pockets at the hip and inside pocket detail. Contrast patch appliqués on the front and back.",
    image: "/Zara/zara10.jpg",
    price: "4290",
  },
  {
    id: 111,
    title:
      "Symbol Premium Men's Wrinkle-Resistant Regular Fit Cotton Formal Shirt",
    desc: "These formal shirts are made out of 100% double ply premium cotton fabric with liquid ammonia and moisture cure treatment that will resist wrinkles, add lustre and make the fabric breathable. The superlative craftsmanship with semi-cutaway collar, French placket, shanked and wrapped buttons, removable collar bones, and high quality interlinings would add on to the finesse of the garment. You may pair it up with a formal trouser and a blazer for a sharp formal look….. or roll up the sleeves and wear it with a chino or a clean Jeans for that smart casual occasion.",
    image: "/Casual/formal1.png",
    price: "1499",
    category: "formal",
  },
  {
    id: 112,
    title: "Symbol Men's Regular Fit Formal Shirt",
    desc: "An Amazon brand, Symbol is built on the pillars of quality, reliability and affordability, offering a range of lifestyle essentials that help you look good every day. This classic formal shirt is crafted with precision in cotton blend and two tone Fil a Fil fabric, to offer enhanced comfort and style, all at a great value. This shirt comes in a combo pack of 2 and is available in a range of colors to choose for any formal to a semi formal ocassion. To complete the look, pair it with an elegant solid formal trouser and brown leather shoes for a lasting impression. Now, look good every day with Symbol fashion essentials.",
    image: "/Casual/formal2.webp",
    price: "549",
    category: "formal",
  },
  {
    id: 113,
    title: "FABRICALLY Men Regular Fit Solid Spread Collar Casual Shirt",
    desc: "Elevate your formal wardrobe with our impeccably crafted men's regular-fit shirt. Tailored from high-quality cotton, this black and brown formal shirt for men exudes sophistication and style. Experience comfort and elegance without breaking the bank all our formal shirts are priced under 500. Make a statement on any occasion with the timeless appeal of our sky-blue shirt for men. Upgrade your ensemble with this versatile and affordable collection of formal shirts, designed to meet your every style need.",
    image: "/Casual/formal3.webp",
    price: "473",
    category: "formal",
  },
  {
    id: 114,
    title: "Style Quotient Women Solid PolyMoss Regular Formal Shirt",
    desc: "ACCENTUATE YOUR LOOK WEARING THIS CHIC AND STYLISH SOLID SHIRT FEATURING A MANDARIN COLLAR AND THREE-QUARTER PUFF SLEEVES. PAIR THIS SHIRT WITH BEIGE TROUSERS AND HEELS TO HAVE A COMPLETE LOOK.",
    image: "/Casual/formal4.webp",
    price: "489",
    category: "formal",
  },
  {
    id: 115,
    title:
      "UptoDate Mens Classic Polycotton Formal Trouser for Men Business Office Wear Pants",
    desc: "Elevate your professional wardrobe with our Classic Polycotton Formal Trouser for Men. Crafted with a premium polycotton blend, these trousers provide exceptional comfort and durability, allowing you to stay focused on your day without sacrificing style. The timeless design exudes sophistication, making it an ideal choice for formal gatherings and office settings. Our trousers are available in a range of sizes to ensure a perfect fit for every body type. The wrinkle-resistant fabric ensures easy maintenance, giving you a polished appearance all day long. From important board meetings to after-work social events, our versatile trousers are designed to make you look and feel your best, no matter the occasion.",
    image: "/Casual/formal5.webp",
    price: "499",
    category: "formal",
  },
  {
    id: 116,
    title: "U-TURN Men's Cotton Solid Formal/Semi Formal Shirt",
    desc: "This Formal shirt offers a professional look for the true business man. It's the perfect day-to-night shirt. Wear it with some slacks to the office and throw on some jeans at night for drinks with the guys. Whatever the occasion this shirt will be your go-to. The style you want and the feel you need all rolled into this shirt. Please check the size chart for more details before ordering Material & Care100% Premium Cotton (Machine Wash Regular)Style Tip Enhance your look by wearing this trendy shirt. Team it with a pair of Chinos and white sneakers for a fun Smart Casual look About the Brand indoPrimo Finding Basic Menswear for daily use can be hard among todays Fast fashion world, where trends change daily. That's why we started IndoPrimo, to create a one stop shop for premium essential clothing for everyday use at rock bottom prices",
    image: "/Casual/formal6.webp",
    price: "378",
    category: "formal",
  },
  {
    id: 117,
    title:
      "IndoPrimo Formal Shirt for Men || Shirt for Men || Men Stylish Shirt || Men Plain Shirt || Men Solid Shirt",
    desc: "This Formal shirt offers a professional look for the true business man. It's the perfect day-to-night shirt. Wear it with some slacks to the office and throw on some jeans at night for drinks with the guys. Whatever the occasion this shirt will be your go-to. The style you want and the feel you need all rolled into this shirt. Please check the size chart for more details before ordering Material & Care100% Premium Cotton (Machine Wash Regular)Style Tip Enhance your look by wearing this trendy shirt. Team it with a pair of Chinos and white sneakers for a fun Smart Casual look About the Brand indoPrimo Finding Basic Menswear for daily use can be hard among todays Fast fashion world, where trends change daily. That's why we started IndoPrimo, to create a one stop shop for premium essential clothing for everyday use at rock bottom prices",
    image: "/Casual/formal7.webp",
    price: "444",
    category: "formal",
  },
  {
    id: 118,
    title: "CINDERS Women Regular Fit Formal Blazer",
    desc: "CINDERS Formal Daily Wear blazer is made of Best-quality fabric which is soft, breathable, and comfortable, also it is popular for women's blazers. It is also versatile and easy to care for, making it a popular choice for everyday wear.",
    image: "/Casual/formal8.webp",
    price: "1499",
    category: "formal",
  },
  {
    id: 119,
    title: "Ryko Formal Shoes for Men Classic Style Shoes(Black)",
    desc: "The style, design, and all the features make this pair of shoes apt for travel. It keeps your feet comfy from inside so you could put them on for endless hours.",
    image: "/Casual/formal9.webp",
    price: "549",
    category: "formal",
  },
  {
    id: 120,
    title: "Prolific Men's Formal Drving Loafer (Size UK 6-13) Brown",
    desc: "Now showcase your gentility with perfection with this amazing pair of formal shoes for men by the named and famed hub of Prolific. With high end decent color, these formal shoes are a must have for every urban man. Crafted from premium quality 100% vegan leather and quality sole, these are comfortable and slip resistant and are bound to stay with you for quite a long time and also assures perfect business class experience. This shoe is crafted with the aid of experienced and skilled designers & craftsmen, who have a deep sense of latest fashion trends. The flawless make and light weight of footwear makes it easy for the wearer to maintain right posture and balance..",
    image: "/Casual/formal10.webp",
    price: "898",
    category: "formal",
  },
  {
    id: 121,
    title: "Symbol Men's Slim Dress Pants",
    desc: "Our range of formal trousers are designed keeping you in mind. With fits and styling that will make you stand apart and prices that will give you great value for your money, symbol formal trousers are simply impossible to say no to.",
    image: "/Casual/formal11.webp",
    price: "899",
    category: "formal",
  },
  {
    id: 122,
    title: "SIRIL Women's Polyester Blend Woven Formal Top",
    desc: "Fabric : Polyester Blend || Inner Fabric : N/A , Style: Formal Full Sleeve Shirt || Work: Woven",
    image: "/Casual/formal12.webp",
    price: "399",
    category: "formal",
  },

  {
    id: 123,
    title: "Style Quotient Women Solid Beige Regular Formal Shirt",
    desc: "Pattern Type : Solid , Sleeve Length : Long Sleeves",
    image: "/Casual/formal13.webp",
    price: "529",
    category: "formal",
  },

  {
    id: 124,
    title: "Style Quotient Women Solid Polycotton Regular Formal Shirt",
    desc: "CLASSIC SOLID FORMAL SHIRT WITH SPREAD COLLAR AND FULL SLEEVE TO ADD TO YOUR BACK-TO-WORK WARDROBE. PAIR IT WITH TIGHT FIT PANTS AND YOU'RE GOOD TO GO.",
    image: "/Casual/formal14.webp",
    price: "479",
    category: "formal",
  },

  {
    id: 125,
    title: "Style Quotient Women Shirt",
    desc: "This shirt is made with high-quality, lightweight fabric, it features a classic spread collar and a button-down placket that gives it a chic and sophisticated look. The full sleeves with cuffs add an element of elegance to the shirt, making it perfect for both casual and formal occasions. The curved bottom hemline adds a touch of femininity and enhances the shirt's overall aesthetic appeal. The red and white stripe pattern is timeless and can be easily paired with a variety of different bottoms, including jeans, skirts, and shorts. The shirt's loose fit makes it comfortable to wear all day long, while the structured design ensures that it maintains its shape and style.",
    image: "/Casual/formal15.webp",
    price: "579",
    category: "formal",
  },
  {
    id: 333,
    title:
      "London Hills Solid Men's Round Neck Cotton Blend Half Sleeve T-Shirts",
    desc: "London Hills Solid Men's Round Neck Cotton Blend Half Sleeve T-Shirts",
    image: "/Seller/seller14.jpg",
    price: "199",
    category: "party",
  },
  {
    id: 334,
    title:
      "Studio Shringaar Men's 100% Pure Cotton Wine Block Printed Knee Length Kurta",
    desc: "We at Studio Shringaar have been making and exporting men's kurtas for the past 30 years. This years of experience, we have achieved expertise in making kurtas for Indian men of all shapes and sizes. We follow strict quality control and believe in using the best available fabrics and other raw materials to make our kurtas. A kurta is an integral part of the Indian man's attire nowadays.",
    image: "/Party/party10.webp",
    price: "811",
    category: "party",
  },
  {
    id: 335,
    title: "MANQ Men's Slim Fit Single Breasted Blazer",
    desc: "Shop from a wide range of Blazer from MANQ. Perfect for office meetings and parties, you could pair it with a stylish shirt to complete the look.",
    image: "/Party/party9.webp",
    price: "2327",
    category: "party",
  },
  {
    id: 336,
    title: "Bollyclues Women's Net Embroidered Semi-Stitched Lehenga Choli",
    desc: "Fabric: 80% Net, 20% Polyester, Closure Type: Drawstring , Sleeve Type: Full Sleeve",
    image: "/Party/party1.webp",
    price: "899",
    category: "party",
  },
  {
    id: 337,
    title:
      "C J Enterprise Women's Pure Kanjivaram Soft Silk Saree for Wedding With Blouse Piece",
    desc: "We present variety of sarees like kanchipuramsilk sarees, kanjeevaramsilk sarees, banarasisilk sarees KanchivaramSilk paithaniSilk etc.",
    image: "/Party/party2.webp",
    price: "681",
    category: "party",
  },
  {
    id: 338,
    title:
      "Pratham Blue Women's Sequins Georgette Fancy Saree With Blouse Piece",
    desc: "Saree Details : Saree Material- Georgette, Saree Length- 6.3 m, Saree Work Type- Sequins Embroidery Lace Work.",
    image: "/Party/party3.webp",
    price: "839",
    category: "party",
  },
  {
    id: 339,
    title: "madhuram textiles Women Rayon A-Line Long Kurti",
    desc: "Occasion Type: Casual; Item Length Description: Ankle-Length; Age Range Description: Adult",
    image: "/Party/party4.webp",
    price: "999",
    category: "party",
  },
  {
    id: 340,
    title: "CK Fashion Men's Waistcoat Slim Fit Dress Vest Wedding Waistcoat",
    desc: "Fashion quality Vest can make you out of ordinary, It is the prefer choice for most customers as a gift, buy it for Father's Day, Christmas Day, Independence Day, April Fool, anniversary, New Year's Day, Valentine's Day, Thanksgiving Day, May Day, Easter Sunday, etc. Classical style for all occasion: Daily Dress, Birthday, Wedding, Engagement, Party, Business, Office, Meeting, Gifts for Men.Perfect for your everyday use, you could pair it with a stylish t-shirt or shirt complete the look.",
    image: "/Party/party5.webp",
    price: "790",
    category: "party",
  },
  {
    id: 341,
    title:
      "9times Mens Blazers Black Coat Sports Jacket for Business Casual Formal Party Wedding Office Wear",
    desc: "Men's black blazer, a versatile and timeless wardrobe essential. A classic black coat that exudes sophistication and style.",
    image: "/Party/party6.webp",
    price: "2299",
    category: "party",
  },

  {
    id: 342,
    title: "FAVOROSKI Men Waistcoat",
    desc: "SIZE GUIDE : Waist coat/Blazer size should be six Inch Over Your Jeans Waist Size (For Eg : If you Wear a thirty size Jeans your Waist coat size should be thirty six)",
    image: "/Party/party7.webp",
    price: "1199",
    category: "party",
  },
  {
    id: 343,
    title: "IndoPrimo Men's Regular Fit Casual Shirt",
    desc: "Slim Fit , Fabric: 100% Cotton , Full Sleeve ,Casual Shirts; High Quality Fabric and Stitching",
    image: "/Party/party8.webp",
    price: "476",
    category: "party",
  },

  {
    id: 344,
    title:
      "BULLMER Black Trendy Front and Back Printed Oversized Round Neck T-Shirt for Men",
    desc: "BULLMER Printed Round Neck Oversized T-shirts is the perfect choice for Men . BULLMER premium quality cotton blended Tshirts makes you feel easier , Best Value , Superior Quality , Comfort Fit , Stretchable , Comfort Wear , Stylish Look . Amazing Bullmer designer collections makes your look smarter.",
    image: "/Seller/seller15.jpg",
    price: "298",
    category: "party",
  },
  {
    id: 345,
    title:
      "Lymio Men Cargo || Men Cargo Pants || Men Cargo Pants Cotton || Cargos for Men (Cargo-01-04)",
    desc: "Men Cargo || Men Cargo Pants || Men Cargo Pants Cotton || Cargos for Men",
    image: "/Seller/seller2.jpg",
    price: "649",
    category: "party",
  },
  {
    id: 346,
    title: "Allen Solly Men's Regular Fit Polo",
    desc: "Ace weekend dressing in this blue solid Polo Neck T-shirt from Allen Solly by Allen Solly.Manufacturer : Aditya Birla Fashion and Retail Limited",
    image: "/Seller/seller3.jpg",
    price: "699",
    category: "party",
  },
  {
    id: 347,
    title:
      "Lymio Casual Shirt for Men|| Shirt for Men|| Men Stylish Shirt (D-Crush-16-23)",
    desc: "Casual Shirt for Men|| Shirt for Men|| Men Stylish Shirt",
    image: "/Seller/seller4.jpg",
    price: "379",
    category: "party",
  },
  {
    id: 348,
    title: "Adidas Men's Clinch-X M Running Shoe",
    desc: "Mesh upper for lightweight and breathability ;These are Men Running Shoes ;Brand: Adidas ;Midsole: lightstrike IMEVA midsole with visible adiprene providing protection from harmful impact forces.",
    image: "/Seller/seller5.jpg",
    price: "1099",
    category: "party",
  },
  {
    id: 349,
    title: "DOCTOR EXTRA SOFT Doctor Ortho Slippers for Women.",
    desc: "Extra Soft, Padded, Comfortable and Cushioned Foot-Bed Enhances Comfort to The Feet. Doctor Extra Soft Slipper Provides You Better Walking Comfort and Also Makes Your Walking Life Easy and Effortlessly",
    image: "/Seller/seller6.jpg",
    price: "399",
    category: "party",
  },
  {
    id: 350,
    title: "ANNI DESIGNER Women Cotton Blend Kurta Set With Dupatta",
    desc: "ANNI DESIGNER Women's Cotton Blend Straight Printed Kurta with Pant & Dupatta (Mang Pink_L_Pink_Large)",
    image: "/Seller/seller7.jpg",
    price: "679",
    category: "party",
  },
  {
    id: 21,
    title: "ANNI DESIGNER Women Kurta with Palazzo",
    desc: "ANNI DESIGNER Women's Cotton Blend Straight Printed Kurta with Palazzo (Chinki Green_L_Green_Large).This set includes: 1 Kurta with 1 Pant || Work : Printed || Neck Style:- Round Neck",
    image: "/Seller/seller1.jpg",
    price: "489",
  },
  {
    id: 22,
    title:
      "Lymio Men Cargo || Men Cargo Pants || Men Cargo Pants Cotton || Cargos for Men (Cargo-01-04)",
    desc: "Men Cargo || Men Cargo Pants || Men Cargo Pants Cotton || Cargos for Men",
    image: "/Seller/seller2.jpg",
    price: "649",
  },
  {
    id: 23,
    title: "Allen Solly Men's Regular Fit Polo",
    desc: "Ace weekend dressing in this blue solid Polo Neck T-shirt from Allen Solly by Allen Solly.Manufacturer : Aditya Birla Fashion and Retail Limited",
    image: "/Seller/seller3.jpg",
    price: "699",
  },
  {
    id: 24,
    title:
      "Lymio Casual Shirt for Men|| Shirt for Men|| Men Stylish Shirt (D-Crush-16-23)",
    desc: "Casual Shirt for Men|| Shirt for Men|| Men Stylish Shirt",
    image: "/Seller/seller4.jpg",
    price: "379",
  },
  {
    id: 25,
    title: "Adidas Men's Clinch-X M Running Shoe",
    desc: "Mesh upper for lightweight and breathability ;These are Men Running Shoes ;Brand: Adidas ;Midsole: lightstrike IMEVA midsole with visible adiprene providing protection from harmful impact forces.",
    image: "/Seller/seller5.jpg",
    price: "1099",
  },
  {
    id: 26,
    title: "DOCTOR EXTRA SOFT Doctor Ortho Slippers for Women.",
    desc: "Extra Soft, Padded, Comfortable and Cushioned Foot-Bed Enhances Comfort to The Feet. Doctor Extra Soft Slipper Provides You Better Walking Comfort and Also Makes Your Walking Life Easy and Effortlessly",
    image: "/Seller/seller6.jpg",
    price: "399",
  },
  {
    id: 27,
    title: "ANNI DESIGNER Women Cotton Blend Kurta Set With Dupatta",
    desc: "ANNI DESIGNER Women's Cotton Blend Straight Printed Kurta with Pant & Dupatta (Mang Pink_L_Pink_Large)",
    image: "/Seller/seller7.jpg",
    price: "679",
  },
  {
    id: 28,
    title: "ONLY Women Sweatshirt",
    desc: "Fabric Composition :: 100% Cotton , Wash Care :: Machine wash,wash light colours separate , Length :: Long",
    image: "/Seller/seller8.jpg",
    price: "979",
  },
  {
    id: 29,
    title:
      "Dr.Ortho Orthopedic Slippers | Acupressure Slippers | Flip-Flops | For Men & Women's Slippers",
    desc: "Effective Pain Relief Dr. Ortho Acupressure Slippers employ the science of acupressure to bring a healthy dose of walking experience into our everyday lives. With regular wear of a minimum of 30 minutes, these orthopaedic slippers can help improve our blood circulation.",
    image: "/Seller/seller9.jpg",
    price: "395",
  },
  {
    id: 30,
    title:
      "Logitech B170 Wireless Mouse, 2.4 GHz with USB Nano Receiver, Optical Tracking, 12-Months Battery Life, Ambidextrous, PC/Mac/Laptop - Black",
    desc: "Reliable Wireless Connection : Enjoy a wireless connection up to 10m away thanks to a plug-and-forget USB mini-receiver, Optical Tracking : The advanced optical tracking features enable ultra precise moves on almost any surface. Required: available USB port, Windows 7, 8, 10 or later, macOS 10.5 or later, Chrome OS, Linux Kernel 2.6+",
    image: "/Seller/seller10.jpg",
    price: "499",
  },
  {
    id: 31,
    title:
      "Symbol Men's Cotton Rich Solid Polo T-Shirt Regular Fit (Available in Plus Size)",
    desc: " Symbol is built on the pillars of quality, reliability and affordability to offer you lifestyle essentials that never go out of fashion. Never out of style, this Symbol classic polo features contrast inner placket as an accent detail. Styled from breathable pique cotton, this polo is cut in an easy regular fit with ribbed collar & sleeves to provide a better grip and high-low hem for extra comfort. Wear it alone or under a jacket to make this collar polo look great.",
    image: "/Seller/seller11.jpg",
    price: "399",
  },

  {
    id: 32,
    title:
      "Leriya Fashion Ethnic Co Ord Set | Casual Wear Pant Top Set | Fancy Co-Ord Set | Full Pair Set | Women Kurta Sets Kurtis | Women Kurta Pant Set | Coord Sets for Women",
    desc: "Package Content:- 1* Top & 1* Wide Leg Pant Sets || Neck:- Collared neck || Sleeve:- Long Sleeve || Two Piece Nightwear: Long Printed Top + Pyjama (Pajama Sets for Women)",
    image: "/Seller/seller12.jpg",
    price: "529",
  },
  {
    id: 33,
    title: "VERO MODA Women's Cotton Round Neck Sweatshirt",
    desc: "Vero Moda Women Cotton%100 Printed Yellow Regular Fit Sweatshirt",
    image: "/Seller/seller13.jpg",
    price: "1225",
  },
  {
    id: 34,
    title:
      "London Hills Solid Men's Round Neck Cotton Blend Half Sleeve T-Shirts",
    desc: "London Hills Solid Men's Round Neck Cotton Blend Half Sleeve T-Shirts",
    image: "/Seller/seller14.jpg",
    price: "199",
  },
  {
    id: 35,
    title:
      "BULLMER Black Trendy Front and Back Printed Oversized Round Neck T-Shirt for Men",
    desc: "BULLMER Printed Round Neck Oversized T-shirts is the perfect choice for Men . BULLMER premium quality cotton blended Tshirts makes you feel easier , Best Value , Superior Quality , Comfort Fit , Stretchable , Comfort Wear , Stylish Look . Amazing Bullmer designer collections makes your look smarter.",
    image: "/Seller/seller15.jpg",
    price: "298",
  },
];

export default BrandData;
